alter table HOTEL_REGISTRATION_CARD add constraint FK_HOTEL_REGISTRATION_CARD_ON_CLIENT foreign key (CLIENT_ID) references HOTEL_CLIENT(ID);
alter table HOTEL_REGISTRATION_CARD add constraint FK_HOTEL_REGISTRATION_CARD_ON_APARTMENTS foreign key (APARTMENTS_ID) references HOTEL_APARTMENTS(ID);
create index IDX_HOTEL_REGISTRATION_CARD_ON_CLIENT on HOTEL_REGISTRATION_CARD (CLIENT_ID);
create index IDX_HOTEL_REGISTRATION_CARD_ON_APARTMENTS on HOTEL_REGISTRATION_CARD (APARTMENTS_ID);
